---
- name: create a network
  google.cloud.gcp_compute_network:
      name: "{{ gcp_network_name }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: network

- name: Create a Firewall
  google.cloud.gcp_compute_firewall:
    name: "{{ gpc_firewall_name }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
    target_tags:
      - "{{ gcp_instance_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: create a address
  google.cloud.gcp_compute_address:
      name: "{{ gcp_address_name }}"
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: address

- name: create a instance
  google.cloud.gcp_compute_instance:
      state: present
      name: "{{ gcp_instance_name }}"
      machine_type: n1-standard-1
      disks:
        - auto_delete: true
          boot: true
          device_name: device1
          initialize_params:
            disk_size_gb: "{{ gcp_disk_size_gb }}"
            source_image: "{{ gcp_source_image }}"
      network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
      tags:
        items:
          - "{{ gcp_instance_name }}"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute

- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=60