---
- name: Get existing network info
  google.cloud.gcp_compute_network_info:
    filters:
      - name = "{{ gcp_network_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: network

- name: Get firewall info from GCP
  google.cloud.gcp_compute_firewall_info:
    filters:
      - name = "{{ gpc_firewall_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: firewall

- name: tear down the instance
  google.cloud.gcp_compute_instance:
      state: absent
      name: "{{ gcp_instance_name }}"
      # machine_type: n1-standard-1
      # disks:
      #   - auto_delete: true
      #     boot: true
      #     device_name: device1
      #     initialize_params:
      #       disk_size_gb: "{{ gcp_disk_size_gb }}"
      #       source_image: "{{ gcp_source_image }}"
      # network_interfaces:
      #     - network: "{{ network }}"
      #       access_configs:
      #         - name: 'External NAT'
      #           nat_ip: "{{ address }}"
      #           type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute

- name: delete the external IP address
  google.cloud.gcp_compute_address:
      name: "{{ gcp_address_name }}"
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent

- name: Tear down the Firewall
  google.cloud.gcp_compute_firewall:
    name: "{{ gpc_firewall_name }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: Tear down the network
  google.cloud.gcp_compute_network:
      name: "{{ gcp_network_name }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent






