---
- name: Setup a simple web server on the GCP Instance
  hosts: all
  connection: ssh
  gather_facts: False
  vars:
    ansible_user: "{{ lookup('env', 'GCP_ANSIBLE_SA') }}" 
    desired_state: present
    gcp_label: test-label
  roles:
    - web_server
