---
- name: Create a storage, networking, firewall rules and server in GCP
  hosts: localhost
  gather_facts: False
  vars:
    desired_state: present
    gcp_label: test-label
  roles:
    - basic_server