---
gcp_project: terraria-usp
gcp_cred_kind: serviceaccount
gcp_cred_file: "{{ lookup('env', 'GCP_SERVICE_ACCT_FILE') }}"
gpc_object_name_prefix: terraria
zone: "us-west1-a"
region: "us-west1"
ansible_ssh_private_key_file: "{{ lookup('env', 'GCP_SSH_PRIVATE_KEY') }}"