---
gcp_project: terraria-usp
gcp_cred_kind: serviceaccount
gcp_cred_file: "{{ lookup('env', 'GCP_SERVICE_ACCT_FILE') }}"
gcp_source_image: 'projects/centos-cloud/global/images/centos-8-v20200504'
gcp_disk_size_gb: 50
gcp_object_name_prefix: cps
gcp_network_name: "{{ gcp_object_name_prefix }}-network-demo"
gcp_address_name: "{{ gcp_object_name_prefix }}-address-demo"
gpc_firewall_name: "{{ gcp_object_name_prefix }}-firewall-demo"
gcp_instance_name: "{{ gcp_object_name_prefix }}-instance-demo"
zone: "us-west1-a"
region: "us-west1"
ansible_ssh_private_key_file: "{{ lookup('env', 'GCP_SSH_PRIVATE_KEY') }}"