---
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: present

- name: Ensure nginx service is running
  become: yes
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Get network info from GCP
  delegate_to: localhost
  google.cloud.gcp_compute_network_info:
    filters:
      - name = "{{ gcp_network_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: network

- name: Open firewall for http
  delegate_to: localhost
  google.cloud.gcp_compute_firewall:
    name: "{{ gpc_firewall_name }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
      - '80'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ desired_state }}"